### ISSUE TITLE
Needs a license file.

### ISSUE THREAD

**Issue by bryan-lunt** [nhomble/yasML#1]
Hello,

I'd like to use your library in some homework to give to students. For that to be possible, it needs a clear license.
I'd really appreciate that!

**Comment by nhomble** [comment]
Hey Bryan, that's awesome. I will confess the code is pretty dusty and is probably hiding some corpses, so keep me up to date as your students use it. If I get time, I'll add some life to this project and make it a more legitimate repo.

**Comment by bryan-lunt** [comment]
Awesome! Thank you so much!
